version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydb']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydb
      - PORT=3000
      - JWT_SECRET=dev-jwt-secret
      - JWT_REFRESH_SECRET=dev-refresh-jwt-secret
      - CORS_ORIGIN=http://localhost:3001,http://localhost:3002
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - app-uploads:/app/uploads
    command: npm run dev

volumes:
  postgres-data:
  app-uploads:
